begin;

alter table if exists public.pesapal_transactions
  drop constraint if exists pesapal_transactions_pkey;

alter table if exists public.pesapal_transactions
  add column if not exists id bigint generated by default as identity;

alter table if exists public.pesapal_transactions
  add constraint pesapal_transactions_pkey primary key (id);

alter table if exists public.pesapal_transactions
  alter column order_tracking_id drop default,
  alter column merchant_reference drop default,
  alter column order_tracking_id type text using order_tracking_id::text,
  alter column merchant_reference type text using merchant_reference::text,
  alter column order_tracking_id drop not null,
  alter column merchant_reference drop not null,
  alter column raw_payload type jsonb using raw_payload::jsonb,
  alter column ipn_body type jsonb using ipn_body::jsonb;

create unique index if not exists pesapal_transactions_order_tracking_id_key
  on public.pesapal_transactions (order_tracking_id);

create unique index if not exists pesapal_transactions_merchant_reference_key
  on public.pesapal_transactions (merchant_reference);

commit;

-- Reference schema for new environments:
--
-- create table public.pesapal_transactions (
--   id bigint generated by default as identity primary key,
--   order_tracking_id text unique,
--   merchant_reference text unique,
--   payment_status text,
--   status_code text,
--   payment_method text,
--   amount numeric,
--   confirmation_code text,
--   description text,
--   call_back_url text,
--   created_date timestamp without time zone,
--   received_at timestamp without time zone,
--   last_notification_method text,
--   raw_payload jsonb,
--   ipn_body jsonb,
--   updated_at timestamp without time zone
-- );
